Convert to multiline comments to avoid gradle confusion
Summary:
gradle mis-read params as task info. Add yaml common multi-line at beginning to avoid mis-process
error: https://github.com/facebook/capi-param-builder/actions/runs/18352391096/job/52275600065

Differential Revision:
D84180850

Privacy Context Container: L1384019

fbshipit-source-id: 30dff839ae3d70b9a4c008a0c40e90340b03c367