Java: fix gradlew wrapper
Summary:
./gradlew build broke as errors

```
./gradlew build
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
Caused by: java.lang.ClassNotFoundException: org.gradle.wrapper.GradleWrapperMain
```
Reinstall the wrapper and update the existing script

Differential Revision: D78910528

fbshipit-source-id: 427f4855f4b132190d8ec9426d9dcdf02240883c