NodeJS: remove package-lock.json from .gitignore for CI/CD
Summary:
As title, nodejs npm ci required package-lock.json
error: https://github.com/facebook/capi-param-builder/actions/runs/17622066124/job/50069835745

Differential Revision: D82129673

fbshipit-source-id: c437e3a1e3322dae05019d1fcdaf3036fa9978fb